name: x-reply-bot

on:
  schedule:
    - cron: "0 */8 * * *"   # every 8 hours (UTC)
  workflow_dispatch: {}

permissions:
  contents: write   # allow committing state files

jobs:
  run:
    runs-on: ubuntu-latest
    concurrency:
      group: x-reply-bot
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
          BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
        run: python bot.py

      - name: Commit state (since_id, user_id)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add state/*.txt || true
          git commit -m "update bot state [skip ci]" || echo "no changes"
          git push
